#!/usr/bin/env python3
"""Enroll the device + server with the project's offline TA and write
include/config.h for the firmware. Secrets stay out of git (config.h and
.creds/ are gitignored). Wi-Fi password comes from $WIFI_PASS or a prompt.

  python firmware/esp8266/tools/gen_config.py --ssid MyWifi --server-host 192.168.1.23
"""
import argparse, getpass, hashlib, os, secrets, sys
from pathlib import Path

HERE = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(HERE.parents[1]))
from hybrid_ecc_auth.protocol.ta import TrustedAuthority

DEVICE, SERVER = "esp8266-001", "server-A"


def c_array(name: str, b: bytes) -> str:
    return f"static const uint8_t {name}[32] = {{" + ", ".join(f"0x{x:02x}" for x in b) + "};"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--ssid", required=True)
    ap.add_argument("--server-host", required=True, help="LAN IP of the machine running hea-server/interop.py")
    ap.add_argument("--server-port", type=int, default=8443)
    ap.add_argument("--new-enrollment", action="store_true", help="discard the saved TA master secret")
    a = ap.parse_args()
    wifi_pass = os.environ.get("WIFI_PASS") or getpass.getpass("Wi-Fi password: ")

    creds_dir = HERE / ".creds"
    creds_dir.mkdir(exist_ok=True, mode=0o700)
    master_file = creds_dir / "master.hex"
    if master_file.exists() and not a.new_enrollment:
        master = bytes.fromhex(master_file.read_text().strip())
    else:
        master = secrets.token_bytes(32)
        fd = os.open(master_file, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
        os.write(fd, master.hex().encode()); os.close(fd)

    ta = TrustedAuthority(master_secret=master)
    creds = ta.enroll_batch([{"identity": DEVICE, "role": "device"}, {"identity": SERVER, "role": "server"}])
    ta.share_mutual_peer_keys(list(creds.values()))
    lam_d = creds[DEVICE].lam.to_bytes(32, "big")
    lam_s = creds[DEVICE].peer_secrets[SERVER].to_bytes(32, "big")
    gen = int.from_bytes(hashlib.sha256(lam_d).digest()[:4], "big")

    def esc(s): return s.replace("\\", "\\\\").replace('"', '\\"')
    out = HERE / "include" / "config.h"
    fd = os.open(out, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    os.write(fd, f'''// GENERATED by tools/gen_config.py -- do not commit.
#pragma once
#include <stdint.h>
#define WIFI_SSID "{esc(a.ssid)}"
#define WIFI_PASS "{esc(wifi_pass)}"
#define SERVER_HOST "{a.server_host}"
#define SERVER_PORT {a.server_port}
#define SERVER_ID "{SERVER}"
#define EPOCH_GENERATION 0x{gen:08x}u
{c_array("LAM_DEVICE", lam_d)}
{c_array("LAM_SERVER", lam_s)}
'''.encode())
    os.close(fd)
    print(f"wrote {out} (device {DEVICE!r}, server {SERVER!r}); TA master secret in {master_file}")


if __name__ == "__main__":
    main()
